[R_packages]
build = [
    "bookdown",
    "kableExtra",
    "tidyverse",
    "tikzDevice",
    "forecast",
    "patchwork",
    "lmtest",
    "nortest",
    "tseries",
]
dev = [
    "languageserver",
]
